markdown: kramdown

title: Ilias D. Sarris
email: Ilias.D.Sarris@outlook.com
logo: "/assets/images/IS (1).png"
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Ilias-D-Sarris.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-feed
  - jekyll-include-cache

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

author:
  name   : "Ilias Sarris"
  avatar : "/assets/images/IDS_256.jpg"
  bio    : >-
    I was born in Florina, Greece, currently living in Greece's 2nd largest city, Thessaloniki. I have also lived in New York, Los Angeles, London, Frankfurt, Hong Kong, and Istanbul.  
  
    I love building technology products that positively affect people's lives, and being part of the ongoing digital transformation, doing my part to ensure that this transformation is inclusive and will be to society's benefit.  
  
    In my free time you can catch me reading, playing chess, or watching films (and exercising, but not as much as I should!).  
  
    You can read more about me in the [About Me](/about/) section.
  location: "Thessaloniki, Greece"
  # linkedin: "ilias-sarris-91105686"
  # twitter: "Ilias_D_Sarris"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin fa-lg"
      url: "https://www.linkedin.com/in/ilias-sarris-91105686/"
    - label: "Twitter"
      icon: "fab fa-twitter fa-lg"
      url: "https://x.com/Ilias_D_Sarris"
    - label: "Email"
      icon: "fa-solid fa-envelope fa-lg"
      # icon: "fas fa-envelope-square"
      url: "mailto:Ilias.D.Sarris@outlook.com"
    # - label: "Resume"
    #   icon: "far fa-fw fa-file-pdf"
    #   # url: "/assets/files/resume-renato-golia.pdf"
    #   url: "/resume/"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin fa-lg"
      url: "https://www.linkedin.com/in/ilias-sarris-91105686/"
    - label: "Twitter"
      icon: "fab fa-twitter fa-lg"
      url: "https://x.com/Ilias_D_Sarris"
    - label: "Email"
      icon: "fa-solid fa-envelope fa-lg"
      # icon: "fas fa-envelope-square"
      url: "mailto:Ilias.D.Sarris@outlook.com"
    # - label: "GitHub"
    #   icon: "fab fa-github fa-lg"
    #   url: "https://github.com/yourusername"
    # - label: "YouTube"
    #   icon: "fab fa-youtube fa-lg"
    #   url: "https://youtube.com/c/yourchannel"
